# Generated by Django 5.1.7 on 2025-04-15 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='rider',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_landmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_university',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_workplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='ride',
            name='comfort_features',
            field=models.JSONField(blank=True, help_text='Features like AC, music, smoking policy, etc.', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cost_splitting',
            field=models.BooleanField(default=True, help_text='Whether to split costs among passengers'),
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='friend_group',
            field=models.CharField(blank=True, help_text='Specific friend group for this ride', max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, only visible to connections/colleagues'),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_workplace_ride',
            field=models.BooleanField(default=False, help_text='Is this ride to/from a workplace?'),
        ),
        migrations.AddField(
            model_name='ride',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ride',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring ride?'),
        ),
        migrations.AddField(
            model_name='ride',
            name='recurring_days',
            field=models.JSONField(blank=True, help_text='Days on which this ride recurs [0-6] where 0 is Monday', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('commute', 'Work Commute'), ('event', 'Event/Meeting'), ('social', 'Social Gathering'), ('errand', 'Errand Run'), ('other', 'Other')], default='commute', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_description',
            field=models.TextField(blank=True, help_text='Description of route, landmarks, etc.'),
        ),
        migrations.AddField(
            model_name='ride',
            name='time_flexibility_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Flexibility in departure time (minutes)'),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_seats',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ride',
            name='workplace_department',
            field=models.CharField(blank=True, help_text='Specific department for workplace rides', max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_note', models.CharField(blank=True, help_text='Special instructions for pickup', max_length=255)),
                ('relationship', models.CharField(choices=[('colleague', 'Colleague'), ('friend', 'Friend'), ('family', 'Family Member'), ('acquaintance', 'Acquaintance'), ('other', 'Other')], default='colleague', help_text='Relationship with the driver', max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount contributed to trip costs', max_digits=8)),
                ('has_contributed', models.BooleanField(default=False, help_text='Whether the passenger has paid their contribution')),
                ('regular_passenger', models.BooleanField(default=False, help_text='Whether this is a regular passenger for recurring rides')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_passengers', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_rides', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
            ],
            options={
                'unique_together': {('ride', 'passenger')},
            },
        ),
        migrations.DeleteModel(
            name='RideRequest',
        ),
    ]
