# Generated by Django 5.1.7 on 2025-04-15 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_bio_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ac_preference',
            field=models.CharField(choices=[('ac_required', 'AC Required'), ('no_ac', 'No AC'), ('no_preference', 'No Preference')], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="User's average rating as driver/passenger", max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='car_color',
            field=models.CharField(blank=True, help_text="Color of the user's car", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='car_model',
            field=models.CharField(blank=True, help_text="Model of the user's car", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_preference',
            field=models.CharField(choices=[('chatty', 'Enjoy Conversation'), ('quiet', 'Prefer Quiet'), ('no_preference', 'No Preference')], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, help_text='Colleagues, friends, etc.', related_name='connected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department or team within the workplace', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_groups',
            field=models.JSONField(blank=True, help_text='Groups of friends for organizing carpools', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_car',
            field=models.BooleanField(default=False, help_text='Whether the user has a car to offer rides'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, help_text='Home address for better ride matching', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='home_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_plate',
            field=models.CharField(blank=True, help_text="License plate of the user's car", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.JSONField(blank=True, help_text="User's saved payment methods", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_days',
            field=models.JSONField(blank=True, help_text='Preferred days for commuting [0-6], where 0 is Monday', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_departure_times',
            field=models.JSONField(blank=True, help_text='Preferred departure times in 24h format', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_music',
            field=models.JSONField(blank=True, help_text='Music preferences for rides', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_preference',
            field=models.CharField(choices=[('no_smoking', 'No Smoking'), ('smoking_allowed', 'Smoking Allowed'), ('no_preference', 'No Preference')], default='no_smoking', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings received'),
        ),
        migrations.AddField(
            model_name='user',
            name='trusted_drivers',
            field=models.ManyToManyField(blank=True, help_text='Drivers you trust and prefer to ride with', related_name='trusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, help_text='Company or institution where you work/study', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace_address',
            field=models.CharField(blank=True, help_text='Complete workplace address', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
